apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
spec:
  containers:
  - name: container-1
    image: nginx
  - name: container-2
    image: busybox
  initContainers:
  - name: init-container-1
    image: alpine